---
title: "R Notebook"
output: html_notebook
---

## R Markdown

This is the Rcode used to analyze the growth rate and decay rate during Treatment Interval. This is both used for the Total Tumor volume as for the Individual lesion dataset.

```{r}
# importing the tumgr library
library(tumgr)
# reading the Total tumor volume or (individual lesions) during treatment intervals for patients 
data <- read.csv('Volume csv created in python')

# Converting 'date_column' to the right format
data$Case.Date.Start <- as.Date(data$Case.Date.Start, format = "%Y-%m-%d")

# numeric date since 1970 to quantify the dates
data$Case.Date.Start <- as.numeric(data$Case.Date.Start)

colnames(data) <- c("name", "date", "size") #changing the column names to the appropriate names
data
```

```{r}
# generate some sample plots 
par(mfrow=c(2, 3))
# using the gdrate on a (slice of the data, with the standard 0.10)
out <- gdrate(data[1:59, ], 0.10, TRUE)
par(mfrow=c(1, 1))
```


```{r}
# Using the gdrate function for the whole data
out <- gdrate(data, 0.10, FALSE)
# summary of cases  
out$models
# descriptive statistics 
out$sumstats
out$results
```

```{r}
# 'out' contains the coefficients 'g'(growth) and 'd'(decay)
g_coefficients <- out$results$g
d_coefficients <- out$results$d

# Plot the 'g' and 'd' distribution histograms
par(mfrow=c(1,2))

# Histogram of g coefficients
hist(g_coefficients, main="Histogram of g Coefficients", xlab="g Coefficients", col="lightblue")

# Histogram of d coefficients
hist(d_coefficients, main="Histogram of d Coefficients", xlab="d Coefficients", col="lightgreen")

```

```{r}
# Create a csv file containing the growth and decay rates during Treatment interval
write.csv(out$results, file = "results_lesions_t.csv", row.names = FALSE)
```

```{r}
```

```         
```
